### ISSUE TITLE
Missing label files

### ISSUE THREAD

**Issue by tomMoral** [sami6mz/shape_n_patterns#1]
Hello,

I am grading your submission and I have an issue with the dataloading.
When running the `ramp-test` after the unzipping the archive, I get
 `FileNotFoundError: [Errno 2] No such file or directory: './data/y_train.csv'

Am I missing a file in the archive or a processing step to generate these files from the `_classes.csv` file in `train/test` folders?

**Comment by sami6mz** [comment]
Hello Thomas,

Yes you're right, `data_processing.ipynb` generates these files from `_classes.csv`, but not when running the `ramp-test` command. I can try to fix this by the beginning of next week.

**Comment by tomMoral** [comment]
Ok, I ran the `data_processing.ipynb` notebook and now I get the correct files.
This instruction should be in the README or the notebook of the challenge.

But I get another error:
```
Traceback (most recent call last):

  File "/home/tom/.local/miniconda/lib/python3.10/site-packages/rampwf/utils/submission.py", line 121, in train_test_submission
    trained_model = problem.workflow.train_submission(

  File "/home/tom/.local/miniconda/lib/python3.10/site-packages/rampwf/workflows/classifier.py", line 26, in train_submission
    clf.fit(X_array[train_is], y_array[train_is])

  File "/home/tom/.local/miniconda/lib/python3.10/site-packages/pandas/core/frame.py", line 3899, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]

  File "/home/tom/.local/miniconda/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)

  File "/home/tom/.local/miniconda/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6176, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")

KeyError: "None of [Index([  0,   1,   2,   3,   4,   5,   6,   8,   9,  10,\n       ...\n       304, 305, 306, 307, 308, 309, 310, 311, 312, 313],\n      dtype='int64', length=292)] are in the [columns]"
```

**Comment by wendysanensta** [comment]
Hello, the error has been fixed and the readme has been updated. The `ramp-test` command should be working now.

**Comment by tomMoral** [comment]
It is now working. Thanks
